Map<String, List<Map<String, dynamic>>> products = {
  'Fruits': [
    {
      'name': 'Red Apple',
      'price': 1.2,
      'description': 'Fresh red apples, hand-picked from the orchard, known for their crisp texture and sweet flavor. Perfect for snacking, baking, or adding to salads.',
      'weight': '1 kg',
      'image': 'https://i.pinimg.com/originals/87/3a/23/873a23ee5803b93d49cee948164804fe.png',
    },
    {
      'name': 'Organic Banana',
      'price': 0.5,
      'description': 'Ripe bananas, rich in potassium and perfect for a quick energy boost. They are great for smoothies, breakfast bowls, or just as a snack on the go.',
      'weight': '1 kg',
      'image': 'https://parspng.com/wp-content/uploads/2023/02/bananapng.parspng.com_.png',
    },
    {
      'name': 'Fresh Orange',
      'price': 0.8,
      'description': 'Juicy oranges packed with vitamin C, ideal for juicing or enjoying fresh. Their refreshing taste makes them a perfect addition to breakfast or snacks.',
      'weight': '1 kg',
      'image': 'https://parspng.com/wp-content/uploads/2022/05/orangepng.parspng.com-7.png',
    },
    {
      'name': 'Sweet Strawberry',
      'price': 2.5,
      'description': 'Fresh strawberries, bursting with flavor and perfect for desserts, salads, or smoothies. They are deliciously sweet and an excellent source of antioxidants.',
      'weight': '500 g',
      'image': 'https://www.pngmart.com/files/21/Aesthetic-Strawberry-PNG-Photo.png',
    },
    {
      'name': 'Green Grapes',
      'price': 3.0,
      'description': 'Sweet green grapes, great for snacking or adding to fruit salads. They are juicy, refreshing, and high in vitamins and minerals.',
      'weight': '1 kg',
      'image': 'https://freepngimg.com/save/134893-fruit-black-grapes-free-transparent-image-hd/658x439',
    },
    {
      'name': 'Ripe Pineapple',
      'price': 3.5,
      'description': 'Sweet ripe pineapple, perfect for tropical fruit salads, smoothies, or as a topping on desserts. They provide a burst of flavor and are rich in vitamins.',
      'weight': '1 kg',
      'image': 'https://purepng.com/public/uploads/large/purepng.com-pineapple-piecespineapplefruitfoodfreshhalvedpiecesfruitycutted-481521633174wn6aw.png',
    },
    {
      'name': 'Juicy Mango',
      'price': 1.5,
      'description': 'Fresh mangoes, known for their juicy sweetness and tropical flavor. They are great in smoothies, salads, or simply enjoyed fresh.',
      'weight': '1 kg',
      'image': 'https://static.vecteezy.com/system/resources/previews/029/200/082/non_2x/mango-transparent-background-free-png.png',
    },
    {
      'name': 'Fresh Watermelon',
      'price': 4.0,
      'description': 'Refreshing watermelon, perfect for hot summer days. Its high water content makes it a hydrating treat, ideal for picnics or desserts.',
      'weight': '2 kg',
      'image': 'https://pngfre.com/wp-content/uploads/watermelon-27-300x289.png',
    },
    {
      'name': 'Green Kiwi',
      'price': 2.0,
      'description': 'Delicious kiwis, known for their unique tart flavor and bright green color. They are great for smoothies, fruit salads, or as a healthy snack.',
      'weight': '500 g',
      'image': 'https://static.vecteezy.com/system/resources/previews/008/532/603/non_2x/kiwi-fruit-cutout-file-png.png',
    },
    {
      'name': 'Fresh Blueberry',
      'price': 3.0,
      'description': 'Fresh blueberries, rich in antioxidants and perfect for snacking, baking, or adding to cereals. Their sweet flavor makes them a favorite among fruit lovers.',
      'weight': '500 g',
      'image': 'https://purepng.com/public/uploads/large/purepng.com-blueberryberryfruitdeliciousdrawingblueberry-33152234542505pip.png',
    },
  ],
  'Vegetables': [
    {
      'name': 'Organic Carrot',
      'price': 0.6,
      'description': 'Fresh carrots, crunchy and sweet, great for snacking, salads, or cooking. They are rich in beta-carotene and other essential nutrients.',
      'weight': '1 kg',
      'image': 'https://static.vecteezy.com/system/resources/previews/029/712/176/non_2x/carrot-transparent-background-png.png',
    },
    {
      'name': 'Fresh Potato',
      'price': 0.4,
      'description': 'Fresh potatoes, versatile and perfect for a variety of dishes including fries, mashed potatoes, and stews. They are a staple in many cuisines.',
      'weight': '1 kg',
      'image': 'https://purepng.com/public/uploads/large/purepng.com-potatopotatofood-cropsvegetablepotatos-1701527311385zrzci.png',
    },
    {
      'name': 'Red Tomato',
      'price': 1.0,
      'description': 'Fresh tomatoes, juicy and flavorful, ideal for salads, sauces, or cooking. They are rich in vitamins and add a burst of flavor to any dish.',
      'weight': '1 kg',
      'image': 'https://freepngimg.com/thumb/tomato/58-tomato-png-image-thumb.png',
    },
    {
      'name': 'Crispy Lettuce',
      'price': 1.2,
      'description': 'Crispy lettuce, perfect for salads or as a garnish. Its light flavor and crunchy texture make it a great addition to any meal.',
      'weight': '500 g',
      'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZBXQRnJezDf04bEbCMJnAZHzeS1Qg3rUDKg&s',
    },
    {
      'name': 'Green Cucumber',
      'price': 0.7,
      'description': 'Fresh cucumbers, refreshing and hydrating, ideal for salads, sandwiches, or pickling. They are low in calories and high in water content.',
      'weight': '1 kg',
      'image': 'https://freepng.pictures/get-logo.php?id=5034',
    },
    {
      'name': 'Fresh Broccoli',
      'price': 2.0,
      'description': 'Fresh broccoli, known for its health benefits and versatility in cooking. It can be steamed, roasted, or added to stir-fries for a nutritious boost.',
      'weight': '500 g',
      'image': 'https://pngimg.com/d/broccoli_PNG72881.png',
    },
    {
      'name': 'Bell Pepper',
      'price': 1.5,
      'description': 'Colorful bell peppers, great for adding flavor and color to dishes. They are sweet, crunchy, and loaded with vitamins and antioxidants.',
      'weight': '500 g',
      'image': 'https://pnghunter.com/get-logo.php?id=8609',
    },
    {
      'name': 'Fresh Spinach',
      'price': 1.8,
      'description': 'Fresh spinach, rich in iron and other essential nutrients. It can be used in salads, smoothies, or cooked as a side dish for added health benefits.',
      'weight': '500 g',
      'image': 'https://www.pngarts.com/files/6/Green-Spinach-Download-Transparent-PNG-Image.png',
    },
    {
      'name': 'Yellow Onion',
      'price': 0.5,
      'description': 'Fresh onions, essential for cooking and adding flavor to a variety of dishes. They come in different varieties and add depth to your meals.',
      'weight': '1 kg',
      'image': 'https://pngimg.com/uploads/onion/onion_PNG3821.png',
    },
    {
      'name': 'Garlic Clove',
      'price': 0.3,
      'description': 'Fresh garlic, known for its strong flavor and health benefits. It is a staple in cooking and adds depth to sauces, marinades, and dishes.',
      'weight': '250 g',
      'image': 'https://static.vecteezy.com/system/resources/previews/027/214/959/non_2x/garlic-garlic-garlic-transparent-background-ai-generated-free-png.png',
    },
  ],

'Fish': [
    {
      'name': 'Salmon',
      'price': 12.0,
      'description': 'Fresh salmon fillet, rich in omega-3 fatty acids and perfect for grilling, baking, or pan-searing. Its rich flavor makes it a favorite among seafood lovers.',
      'weight': '500 g',
      'image': 'https://www.pngplay.com/wp-content/uploads/15/Salmon-Transparent-File.png',
    },
    {
      'name': 'Tuna',
      'price': 10.0,
      'description': 'Fresh tuna fillet, meaty and flavorful, ideal for grilling or making sushi. It is a versatile fish that can be enjoyed raw or cooked.',
      'weight': '500 g',
      'image': 'https://static.vecteezy.com/system/resources/thumbnails/033/050/049/small_2x/ai-generative-raw-tuna-steak-isolated-on-transparent-background-png.png',
    },
    {
      'name': 'Trout',
      'price': 8.0,
      'description': 'Fresh trout, known for its delicate flavor and tender texture. It can be grilled, baked, or pan-fried for a delicious meal.',
      'weight': '500 g',
      'image': 'https://sb-assets.sgp1.cdn.digitaloceanspaces.com/product/main_image/64814/small_60514c16-0947-4e02-b508-a46742a2e8a2.png',
    },
    {
      'name': 'Cod',
      'price': 9.0,
      'description': 'Fresh cod fillet, flaky and mild in flavor. It is perfect for baking or frying and pairs well with a variety of seasonings and sauces.',
      'weight': '500 g',
      'image': 'https://www.seacoreseafood.com/pictures/product_tbn_yDPnLlTM4c.png',
    },
    {
      'name': 'Mackerel',
      'price': 7.0,
      'description': 'Fresh mackerel, rich in healthy fats and flavor. It is great for grilling or smoking, and its robust taste stands up well to bold seasonings.',
      'weight': '500 g',
      'image': 'https://seafoodonline.ca/cdn/shop/products/Atlantic_Mackerel_2000x.png?v=1624647625',
    },
    {
      'name': 'Sardine',
      'price': 6.0,
      'description': 'Fresh sardines, small and flavorful, perfect for grilling or canning. They are rich in omega-3s and make a tasty addition to salads and sandwiches.',
      'weight': '500 g',
      'image': 'https://www.pngplay.com/wp-content/uploads/9/Sardines-Transparent-PNG.png',
    },
  ],
  'Meat': [
    {
      'name': 'Chicken Breast',
      'price': 8.0,
      'description': 'Fresh chicken breast, lean and versatile, perfect for grilling, baking, or stir-frying. It is a great source of protein and can be used in a variety of dishes.',
      'weight': '1 kg',
      'image': 'https://www.grassfedmeatsontario.com/cdn/shop/products/Chicken-Meat-PNG-Image-with-Transparent-Background_4b8d6f0d-18f6-4b14-b1df-0de6938f5407_600x.png?v=1569388857',
    },
    {
      'name': 'Ground Beef',
      'price': 9.0,
      'description': 'Fresh ground beef, rich in flavor and perfect for making burgers, meatballs, or sauces. It is a staple for many hearty meals.',
      'weight': '1 kg',
      'image': 'https://pngimg.com/d/beef_PNG51.png',
    },
    {
      'name': 'Pork Chops',
      'price': 11.0,
      'description': 'Fresh pork chops, tender and juicy, ideal for grilling or pan-frying. They are flavorful and can be seasoned in various ways for delicious meals.',
      'weight': '1 kg',
      'image': 'https://static.vecteezy.com/system/resources/previews/035/642/302/non_2x/ai-generated-raw-pork-chop-free-png.png',
    },
    {
      'name': 'Lamb Chops',
      'price': 15.0,
      'description': 'Fresh lamb chops, known for their rich flavor and tenderness. They are perfect for grilling or roasting and pair well with various herbs and spices.',
      'weight': '1 kg',
      'image': 'https://classichalal.com/wp-content/uploads/2020/04/lambchops.png',
    },
    {
      'name': 'Turkey',
      'price': 10.0,
      'description': 'Fresh turkey, a lean source of protein ideal for roasting or grilling. It is great for special occasions or as a healthy alternative to red meat.',
      'weight': '1 kg',
      'image': 'https://img.pikbest.com/origin/09/18/53/11cpIkbEsTSj8.png!sw800',
    },
    {
      'name': 'Beef Steak',
      'price': 18.0,
      'description': 'Fresh beef steak, rich in flavor and perfect for grilling or pan-searing. Its tenderness makes it a favorite for steak lovers.',
      'weight': '1 kg',
      'image': 'https://static.vecteezy.com/system/resources/previews/035/277/207/non_2x/ai-generated-fresh-raw-beef-steak-isolated-on-a-transparent-background-png.png',
    },
    {
      'name': 'Bacon',
      'price': 12.0,
      'description': 'Crispy bacon, perfect for breakfast or adding flavor to dishes. It is deliciously salty and smoky, making it a popular choice among many.',
      'weight': '500 g',
      'image': 'https://static.vecteezy.com/system/resources/previews/040/190/700/non_2x/ai-generated-bacon-clip-art-free-png.png',
    },
    {
      'name': 'Duck Breast',
      'price': 20.0,
      'description': 'Fresh duck breast, rich and flavorful, ideal for gourmet dishes. It can be roasted or grilled and pairs well with sweet and savory sauces.',
      'weight': '500 g',
      'image': 'https://lafromageriesf.com/cdn/shop/products/unnamed_5_1000x1000.png?v=1593200288',
    },
    {
      'name': 'Sausages',
      'price': 7.0,
      'description': 'Delicious sausages, perfect for grilling or adding to stews. They come in various flavors and are a favorite at barbecues.',
      'weight': '1 kg',
      'image': 'https://res.cloudinary.com/kraft-heinz-whats-cooking-ca/image/upload/f_auto/q_auto/r_8/c_limit,w_3840/f_auto/q_auto/v1/dxp-images/oscarmayer/products/00990016700332-bun-length-plant-based-not-hot-dogs/marketing-view-color-front_content-hub-10345131_3296e4a39ae72877a0336b8dae6d4363?_a=BAVAfVIB0',
    },
  ],
};
